#!/usr/bin/env bash

if [ -n "$WWWUSER" ]; then
    usermod -u "$WWWUSER" sail
fi

if [ -n "$WWWGROUP" ]; then
    groupmod -o -g "$WWWGROUP" sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
